import type { Command } from "commander";
import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { DEFAULT_ADR_CONFIG, readAdrConfig, readMarkdownTitle } from "../adr.ts";

export function registerSyncCommand(program: Command) {
  program
    .command("sync")
    .description(`Generate ${DEFAULT_ADR_CONFIG.indexFileName} inside the ADR directory`)
    .action(syncAdrIndex);
}

export async function syncAdrIndex() {
  const config = await readAdrConfig();
  const resolvedDir = path.resolve(process.cwd(), config.directory);
  const entries = await readdir(resolvedDir, { withFileTypes: true });
  const indexFileName = config.indexFileName.toLowerCase();

  const adrFiles = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => name.toLowerCase().endsWith(".md"))
    .filter((name) => name.toLowerCase() !== indexFileName)
    .sort((a, b) => a.localeCompare(b));

  const items = await Promise.all(
    adrFiles.map(async (fileName) => {
      const title = await readMarkdownTitle(path.join(resolvedDir, fileName));
      return `* [${adrId(fileName)}](${encodeURI(fileName)}) - ${title}`;
    }),
  );

  const index = [
    "<!--",
    "  This file was automatically generated.",
    "  DO NOT EDIT THIS FILE DIRECTLY. Any changes will be overwritten.",
    "-->",
    "",
    "# Architecture Decision Records",
    "",
    "This repository serves as a log of the significant architectural decisions made during the design and evolution of our system. Each record (ADR) captures the context, considered options, trade-offs, and final outcomes to provide a transparent history of our technical choices.",
    "",
    items.length > 0 ? items.join("\n") : "No ADR markdown files found.",
    "",
  ].join("\n");

  await writeFile(path.join(resolvedDir, config.indexFileName), index, "utf8");
  console.log(`Generated ${path.join(config.directory, config.indexFileName)}`);
}

function adrId(fileName: string) {
  const number = /^(\d+)(?:[-_ ].*)?\.md$/i.exec(fileName)?.[1];
  return number ? `ADR-${number}` : "ADR";
}
